/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Slug = string;
export type Tag = string;
export type Tags = Tag[];
export type MetadataTitle = string;
export type MetadataDescription = string;
export type Public = boolean;
export type Block =
  | {
      html: string;
    }
  | {
      images: {
        [k: string]: unknown;
      }[];
    };

export interface EditPost {
  title: Title;
  slug?: Slug;
  tags?: Tags;
  metadata?: Metadata;
  public?: Public;
  content?: Block[];
  [k: string]: unknown;
}
export interface Metadata {
  title?: MetadataTitle;
  description?: MetadataDescription;
}
