/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ContactSchema {
  id?: number | null;
  email?: string | null;
  socialmedia?: SocialMediaSchema[];
  [k: string]: unknown;
}
export interface SocialMediaSchema {
  id?: number;
  platform?: string | null;
  profileUrl?: string | null;
  username?: string | null;
  [k: string]: unknown;
}
