/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ImageRefSchema {
  etag?: string;
  public_id?: string;
  mediaType?: "IMAGE" | "VIDEO" | "THREE_D";
  cld_url?: string;
  path?: string;
  filename?: string;
  format?: string;
  bytes?: number;
  description?: string;
  width?: number;
  height?: number;
  createdAt?: string;
  updatedAt?: string | null;
  [k: string]: unknown;
}
