/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Block = Text | Image | Video;
export type Content = Block[];

export interface PostSchema {
  id?: number;
  html?: Content;
  generalId?: number;
  authorEmail?: string;
  [k: string]: unknown;
}
export interface Text {
  text?: string;
  [k: string]: unknown;
}
export interface Image {
  images?: unknown[];
  [k: string]: unknown;
}
export interface Video {
  videos?: unknown[];
  [k: string]: unknown;
}
