/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PreferencesSchema {
  creator_name?: string;
  homepage_heading?: string;
  homepage_subheading?: string;
  homepage_background_image?: {
    [k: string]: unknown;
  } | null;
  homepage_background_video?: {
    [k: string]: unknown;
  } | null;
  enable_dashboard_darkmode?: boolean;
  enable_portfolio_pdf?: boolean;
  createdAt?: string;
  updatedAt?: string | null;
  [k: string]: unknown;
}
