/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProfileSchema {
  html_statement?: string | null;
  html_additional?:
    | {
        html?: string;
        [k: string]: unknown;
      }[]
    | null;
  contact?: Contact[];
  /**
   * e.g. https://archive.org/details/jakubkanna_PORTFOLIO_2024
   */
  portfolio_pdf_url?: string | null;
  [k: string]: unknown;
}
export interface Contact {
  id?: number | null;
  email?: string | null;
  socialmedia?: SocialMedia[];
  [k: string]: unknown;
}
export interface SocialMedia {
  id?: number;
  platform?: string | null;
  profileUrl?: string | null;
  username?: string | null;
  [k: string]: unknown;
}
