/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ProjectSchema {
  id?: number;
  subtitle?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  venue?: string | null;
  images?: {
    [k: string]: unknown;
  }[];
  videos?: {
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
