/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Slug = string;
export type Tags = string[];
export type Public = boolean;
export type Medium = string[];
export type Year = number;
export type Events = {
  [k: string]: unknown;
}[];
export type Images = {
  [k: string]: unknown;
}[];

export interface EditWork {
  general: General;
  details: Details;
  [k: string]: unknown;
}
export interface General {
  title: Title;
  slug?: Slug;
  tags?: Tags;
  public?: Public;
  [k: string]: unknown;
}
export interface Details {
  medium: Medium;
  year: Year;
  events: Events;
  images: Images;
  [k: string]: unknown;
}
