/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Name = string;
export type Domain = string;
export type Header = string;
export type Subheader = string;
export type DarkMode = boolean;
export type APIURL = string;
export type EnableCLD = boolean;
export type HTTPSProtocol = boolean;
export type HTML = string;
export type ID = string;
export type Title = string;
export type HTML1 = string;
export type Additional = AdditionalItem[];
export type ID1 = string;
export type Email = string;
export type ID2 = string;
export type Name1 = string;
export type ProfileURL = string;
export type Username = string;
export type SocialMedia = SocialMediaItem[];
export type Contact = ContactItem[];

export interface Root {
  general?: General;
  profile?: Profile;
  [k: string]: unknown;
}
export interface General {
  website?: Website;
  dashboard?: Dashboard;
  apis?: APIs;
  security?: Security;
  [k: string]: unknown;
}
export interface Website {
  details?: Details;
  homepage?: Homepage;
  [k: string]: unknown;
}
export interface Details {
  name?: Name;
  domain?: Domain;
  favicon?: Favicon;
  [k: string]: unknown;
}
export interface Favicon {
  [k: string]: unknown;
}
export interface Homepage {
  header?: Header;
  subheader?: Subheader;
  background?: Background;
  metadata?: Metadata;
  [k: string]: unknown;
}
export interface Background {
  [k: string]: unknown;
}
export interface Metadata {
  title?: string;
  description?: string;
  [k: string]: unknown;
}
export interface Dashboard {
  dark_mode?: DarkMode;
  [k: string]: unknown;
}
export interface APIs {
  server?: Server;
  youtube?: Youtube;
  cld?: CLD;
  [k: string]: unknown;
}
export interface Server {
  api_url?: APIURL;
  [k: string]: unknown;
}
export interface Youtube {
  api_key?: string;
  [k: string]: unknown;
}
export interface CLD {
  enable?: EnableCLD;
  [k: string]: unknown;
}
export interface Security {
  https_protocol?: HTTPSProtocol;
  [k: string]: unknown;
}
export interface Profile {
  bio?: Bio;
  contact?: Contact;
  portfolio_pdf?: PortfolioPDF;
  [k: string]: unknown;
}
export interface Bio {
  statement?: Statement;
  additional?: Additional;
  [k: string]: unknown;
}
export interface Statement {
  html?: HTML;
  [k: string]: unknown;
}
export interface AdditionalItem {
  _id?: ID;
  title?: Title;
  html?: HTML1;
  [k: string]: unknown;
}
export interface ContactItem {
  _id?: ID1;
  email?: Email;
  socialmedia?: SocialMedia;
  [k: string]: unknown;
}
export interface SocialMediaItem {
  _id?: ID2;
  platform?: Platform;
  [k: string]: unknown;
}
export interface Platform {
  name?: Name1;
  profile_url?: ProfileURL;
  username?: Username;
  [k: string]: unknown;
}
/**
 * Check if you would like to display portfolio button on the website.
 */
export interface PortfolioPDF {
  enable?: boolean;
  [k: string]: unknown;
}
