/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Schema {
  generalSection?: GeneralSection;
  ImageRef?: ImageRef;
  VideoRef?: VideoRef;
  post?: Post;
  preferences?: Preferences;
  project?: Project;
  tag?: Tag;
  socialMedia?: SocialMedia;
  contact?: Contact;
  profile?: Profile;
  user?: User;
  work?: Work;
  [k: string]: unknown;
}
export interface GeneralSection {
  id?: number;
  title?: string;
  description?: string | null;
  published?: boolean;
  slug?: string;
  createdAt?: string;
  updatedAt?: string | null;
  [k: string]: unknown;
}
export interface ImageRef {
  etag?: string;
  public_id?: string;
  type?: "IMAGE" | "VIDEO" | "THREE_D";
  cld_url?: string;
  filename?: string | null;
  format?: string | null;
  bytes?: number | null;
  description?: string | null;
  width?: number | null;
  height?: number | null;
  createdAt?: string;
  updatedAt?: string | null;
  preferencesId?: number | null;
  [k: string]: unknown;
}
export interface VideoRef {
  etag?: string;
  type?: "IMAGE" | "VIDEO" | "THREE_D";
  id?: string | null;
  vimeo_url?: string | null;
  sc_url?: string | null;
  yt_url?: string | null;
  title?: string | null;
  duration?: string | null;
  definition?: string | null;
  description?: string | null;
  thumbnail?: string | null;
  player_loop?: boolean;
  player_muted?: boolean;
  createdAt?: string;
  updatedAt?: string | null;
  preferencesId?: number | null;
  [k: string]: unknown;
}
export interface Post {
  id?: number;
  html?: string;
  generalId?: number;
  authorId?: number;
  [k: string]: unknown;
}
export interface Preferences {
  id?: number;
  creator?: string;
  domain?: string;
  homepage_heading?: string;
  homepage_subheading?: string;
  enable_dashboard_darkmode?: boolean;
  enable_portfolio_pdf?: boolean;
  createdAt?: string;
  updatedAt?: string | null;
  imageRefEtag?: string | null;
  videoRefEtag?: string | null;
  [k: string]: unknown;
}
export interface Project {
  id?: number;
  subtitle?: string;
  start_date?: string;
  end_date?: string;
  venue?: string;
  generalId?: number;
  createdAt?: string;
  updatedAt?: string | null;
  [k: string]: unknown;
}
export interface Tag {
  id?: number;
  name?: string;
  [k: string]: unknown;
}
export interface SocialMedia {
  id?: number;
  platform?: string | null;
  profileUrl?: string | null;
  username?: string | null;
  contactId?: number;
  [k: string]: unknown;
}
export interface Contact {
  id?: number;
  email?: string | null;
  userId?: number;
  [k: string]: unknown;
}
export interface Profile {
  userId?: number;
  html_statement?: string | null;
  html_additional?: string | null;
  portfolio_pdf?: string | null;
  [k: string]: unknown;
}
export interface User {
  id?: number;
  email?: string;
  hash?: string;
  salt?: string;
  [k: string]: unknown;
}
export interface Work {
  id?: number;
  dimensions?: string | null;
  year?: number | null;
  generalId?: number;
  createdAt?: string;
  updatedAt?: string | null;
  [k: string]: unknown;
}
